#!/usr/bin/env python3
# encoding: utf-8
"""Minimal ``[[ name ]]`` placeholder rendering for operator-authored USM ticket templates.

Deliberately not Jinja2. The templates come from ``case-reasoning.yml``, which is written by
operators (and, increasingly, generated by the SOC Use Cases Management Tool) and travels
through Consul KV — so the renderer must not evaluate arbitrary expressions, and the
responders must not grow a dependency that changes the Cortex image's Python environment.

``[[ ]]`` rather than ``{{ }}`` is a hard requirement, not a style choice: the YAML is
rendered by consul-template with the *default* delimiters (``sirp/thehive-setup.nomad.hcl``
sets no ``left_delimiter`` for this file, unlike its siblings), so a ``{{ ... }}`` in a
template would be consumed at deploy time and never reach the responder.

Names may be dotted (``cf.internal-ref``) to reach into a nested context. An unknown name
renders as the empty string and is reported back to the caller, so a typo shows up as a log
line on the case rather than as a silently mangled ticket.
"""
import re

# Dots reach into nested context dicts; '-' is allowed because TheHive custom-field names use it.
PLACEHOLDER = re.compile(r"\[\[\s*([A-Za-z0-9_][A-Za-z0-9_.\-]*)\s*\]\]")


def _lookup(context, name):
    """Resolve a possibly-dotted name against the context. Returns (found, value)."""
    node = context
    for part in name.split("."):
        if not isinstance(node, dict) or part not in node:
            return False, None
        node = node[part]
    return True, node


def render(text, context, unknown=None):
    """Substitute every ``[[ name ]]`` in ``text`` with its context value.

    ``unknown``, when given a set, collects the names that had no context entry (they render
    as ""). A value of None also renders as "" — a context key that exists but is unset is a
    normal outcome (e.g. a case with no description), not a template error.
    """

    def substitute(match):
        name = match.group(1)
        found, value = _lookup(context, name)
        if not found:
            if unknown is not None:
                unknown.add(name)
            return ""
        return "" if value is None else str(value)

    return PLACEHOLDER.sub(substitute, text)


def render_payload(template, context):
    """Render a USM template mapping into a ticket payload. Returns ``(payload, unknown_names)``.

    Only string values are rendered; anything else (bool, number, or an explicit null used to
    drop a default key) is passed through untouched, so a template can set a literal USM field
    without it going through substitution.
    """
    if not isinstance(template, dict):
        return {}, []
    unknown = set()
    payload = {}
    for key, value in template.items():
        payload[key] = render(value, context, unknown) if isinstance(value, str) else value
    return payload, sorted(unknown)
